// mashen.dev — hero content (subset of portfolio.ts), i18n EN/TR/NL
// Attaches to window.HERO
window.HERO = {
  identity: {
    name: 'M. Ali ŞEN',
    handle: 'mashen.dev',
    email: 'muhalishen@gmail.com',
    location: 'Flanders, Belgium',
    github: 'shenmali',
    linkedin: 'alimshen',
  },

  // Nodes for the agentic graph. `kind` drives color weight; `hub` nodes are larger.
  graph: [
    { id: 'agent',   label: 'AGENT',      kind: 'core', hub: true },
    { id: 'llm',     label: 'LLM',        kind: 'core', hub: true },
    { id: 'rag',     label: 'RAG',        kind: 'core', hub: true },
    { id: 'langgraph', label: 'LangGraph', kind: 'orch' },
    { id: 'mcp',     label: 'MCP',        kind: 'orch' },
    { id: 'crewai',  label: 'CrewAI',     kind: 'orch' },
    { id: 'n8n',     label: 'n8n',        kind: 'auto' },
    { id: 'temporal',label: 'Temporal',   kind: 'auto' },
    { id: 'flux',    label: 'FLUX',       kind: 'gen' },
    { id: 'comfy',   label: 'ComfyUI',    kind: 'gen' },
    { id: 'lora',    label: 'LoRA',       kind: 'gen' },
    { id: 'neo4j',   label: 'Neo4j',      kind: 'data' },
    { id: 'qdrant',  label: 'Qdrant',     kind: 'data' },
    { id: 'pgvector',label: 'pgvector',   kind: 'data' },
    { id: 'claude',  label: 'Claude',     kind: 'core' },
    { id: 'langfuse',label: 'Langfuse',   kind: 'ops' },
    { id: 'pytorch', label: 'PyTorch',    kind: 'ml' },
    { id: 'mcp2',    label: 'tool-use',   kind: 'orch' },
  ],
  // edges by id pairs
  edges: [
    ['agent','llm'], ['agent','langgraph'], ['agent','mcp'], ['agent','crewai'],
    ['llm','rag'], ['llm','claude'], ['rag','neo4j'], ['rag','qdrant'], ['rag','pgvector'],
    ['langgraph','mcp'], ['mcp','mcp2'], ['mcp','claude'], ['agent','n8n'], ['n8n','temporal'],
    ['gen','flux'], ['flux','comfy'], ['comfy','lora'], ['agent','flux'], ['llm','langfuse'],
    ['rag','pytorch'], ['crewai','n8n'], ['claude','mcp2'], ['agent','rag'], ['flux','lora'],
  ],

  focusCodes: ['AGT', 'AUT', 'RAG', 'GEN', 'DEV', 'L10N', 'OPS', 'FCST', 'GAME'],

  ui: {
    en: {
      role: 'AI/ML Engineer // Data Scientist',
      eyebrow: 'AI / ML · GENERATIVE · AGENTIC · MULTI-MODAL',
      status: 'system // online',
      latency: 'available for work',
      // Matrix-style intro, typed line by line
      intro: [
        'Wake up, admin…',
        'The simulation has you.',
        'Follow the gradient.',
      ],
      // terminal narrative (typed) in the hero
      narrative: [
        { t: '> consciousness.boot()', cls: 'dim' },
        { t: '> you are inside an artificial universe.', cls: '' },
        { t: '> billions of parameters humming around you.', cls: '' },
        { t: '> most who enter stay NPCs — prompt in, tokens out.', cls: 'muted' },
        { t: '> a few rewrite the simulation itself.', cls: 'accent' },
        { t: '', cls: '' },
        { t: '> identify  M. Ali ŞEN — AI/ML Engineer', cls: '' },
        { t: '> clearance root // sudo enabled', cls: 'accent' },
      ],
      question: 'Ready to be a SuperUser — not an NPC — in the AI world?',
      yes: 'sudo su —  ENTER',
      no: 'stay npc',
      headline1: 'Pipelines that',
      headlineEm1: 'think,',
      headline2: 'assets that',
      headlineEm2: 'ship.',
      grantedTitle: 'ACCESS GRANTED',
      grantedSub: 'root@mashen — welcome to the control plane.',
      cta: { contact: 'Get in touch', cv: 'Download CV', github: 'GitHub' },
      denied: 'denied. respawning NPC…',
      hint: 'click anywhere to skip',
    },
    tr: {
      role: 'AI/ML Mühendisi // Data Scientist',
      eyebrow: 'AI / ML · ÜRETKEN · AGENTIC · ÇOK-MODLU',
      status: 'sistem // çevrimiçi',
      latency: 'işe açık',
      intro: [
        'Uyan, admin…',
        'Simülasyon seni ele geçirdi.',
        "Gradyan'ı takip et.",
      ],
      narrative: [
        { t: '> bilinc.boot()', cls: 'dim' },
        { t: '> yapay bir evrenin içindesin.', cls: '' },
        { t: '> etrafında milyarlarca parametre uğulduyor.', cls: '' },
        { t: '> girenlerin çoğu NPC kalır — prompt girer, token çıkar.', cls: 'muted' },
        { t: '> birkaçı simülasyonun kendisini yeniden yazar.', cls: 'accent' },
        { t: '', cls: '' },
        { t: '> kimlik  M. Ali ŞEN — AI/ML Mühendisi', cls: '' },
        { t: '> yetki root // sudo etkin', cls: 'accent' },
      ],
      question: 'AI dünyasında NPC değil, SuperUser olmaya hazır mısın?',
      yes: 'sudo su —  GİRİŞ',
      no: 'npc kal',
      headline1: 'Düşünen',
      headlineEm1: "pipeline'lar,",
      headline2: 'teslim edilen',
      headlineEm2: "asset'ler.",
      grantedTitle: 'ERİŞİM VERİLDİ',
      grantedSub: 'root@mashen — kontrol düzlemine hoş geldin.',
      cta: { contact: 'İletişime geç', cv: 'CV indir', github: 'GitHub' },
      denied: 'reddedildi. NPC yeniden doğuyor…',
      hint: 'geçmek için tıkla',
    },
    nl: {
      role: 'AI/ML Engineer // Data Scientist',
      eyebrow: 'AI / ML · GENERATIEF · AGENTIC · MULTIMODAAL',
      status: 'systeem // online',
      latency: 'beschikbaar voor werk',
      intro: [
        'Word wakker, admin…',
        'De simulatie heeft je.',
        'Volg de gradiënt.',
      ],
      narrative: [
        { t: '> bewustzijn.boot()', cls: 'dim' },
        { t: '> je bevindt je in een kunstmatig universum.', cls: '' },
        { t: '> miljarden parameters zoemen om je heen.', cls: '' },
        { t: '> de meesten blijven NPCs — prompt in, tokens uit.', cls: 'muted' },
        { t: '> enkelen herschrijven de simulatie zelf.', cls: 'accent' },
        { t: '', cls: '' },
        { t: '> identiteit  M. Ali ŞEN — AI/ML Engineer', cls: '' },
        { t: '> clearance root // sudo aan', cls: 'accent' },
      ],
      question: 'Klaar om een SuperUser te zijn — geen NPC — in de AI-wereld?',
      yes: 'sudo su —  ENTER',
      no: 'blijf npc',
      headline1: 'Pijplijnen die',
      headlineEm1: 'denken,',
      headline2: 'assets die',
      headlineEm2: 'verschepen.',
      grantedTitle: 'TOEGANG VERLEEND',
      grantedSub: 'root@mashen — welkom in het control plane.',
      cta: { contact: 'Neem contact op', cv: 'CV downloaden', github: 'GitHub' },
      denied: 'geweigerd. NPC respawnt…',
      hint: 'klik om over te slaan',
    },
  },
};
